import {
  Users,
  Globe,
  Compass,
  ShieldAlert,
  Scale,
  ShieldCheck,
  Server,
  Package,
  Cpu,
  KeyRound,
  Timer,
  CloudLightning,
  Plug,
  Database,
  Zap,
  Radio,
  HardDrive,
} from 'lucide-react';
import type { NodeType, NodeTypeConfig } from '@/types';

export const NODE_CONFIG: Record<NodeType, NodeTypeConfig> = {
  user: {
    label: 'User / Client',
    Icon: Users,
    accent: '#3b82f6',
    category: 'infrastructure',
    defaultTechnology: 'Browser / Mobile',
    defaultName: 'Client',
    description: 'End-user or client application. Entry point of the system.',
    allowedTargets: ['cdn', 'dns', 'loadBalancer', 'apiGateway'],
  },
  cdn: {
    label: 'CDN',
    Icon: Globe,
    accent: '#8b5cf6',
    category: 'infrastructure',
    defaultTechnology: 'CloudFront / Cloudflare',
    defaultName: 'CDN',
    description: 'Content Delivery Network. Caches and serves static assets close to the user.',
    allowedTargets: ['loadBalancer', 'apiGateway', 'apiServer'],
  },
  dns: {
    label: 'DNS',
    Icon: Compass,
    accent: '#06b6d4',
    category: 'infrastructure',
    defaultTechnology: 'Route53 / Cloudflare DNS',
    defaultName: 'DNS',
    description: 'Resolves domain names to IP addresses. Often the first hop for a request.',
    allowedTargets: ['cdn', 'waf', 'loadBalancer', 'apiGateway'],
  },
  waf: {
    label: 'WAF',
    Icon: ShieldAlert,
    accent: '#dc2626',
    category: 'infrastructure',
    defaultTechnology: 'AWS WAF / Cloudflare WAF',
    defaultName: 'WAF',
    description: 'Filters malicious traffic before it reaches your infrastructure.',
    allowedTargets: ['cdn', 'loadBalancer', 'apiGateway'],
  },
  loadBalancer: {
    label: 'Load Balancer',
    Icon: Scale,
    accent: '#f97316',
    category: 'infrastructure',
    defaultTechnology: 'Nginx / HAProxy',
    defaultName: 'Load Balancer',
    description: 'Distributes incoming traffic across multiple servers for availability.',
    allowedTargets: ['apiGateway', 'apiServer', 'microservice'],
  },
  apiGateway: {
    label: 'API Gateway',
    Icon: ShieldCheck,
    accent: '#14b8a6',
    category: 'infrastructure',
    defaultTechnology: 'Kong / AWS API Gateway',
    defaultName: 'API Gateway',
    description: 'Single entry point for APIs. Handles auth, rate limiting, routing.',
    allowedTargets: ['apiServer', 'microservice', 'authService'],
  },
  apiServer: {
    label: 'API Server',
    Icon: Server,
    accent: '#22c55e',
    category: 'services',
    defaultTechnology: 'Node.js / Go',
    defaultName: 'API Server',
    description: 'Handles business logic, processes requests, returns responses.',
    allowedTargets: ['microservice', 'database', 'cache', 'messageQueue', 'storage', 'authService', 'thirdPartyApi'],
  },
  microservice: {
    label: 'Microservice',
    Icon: Package,
    accent: '#10b981',
    category: 'services',
    defaultTechnology: 'Docker / Kubernetes',
    defaultName: 'Service',
    description: 'Independently deployable service owning a bounded domain context.',
    allowedTargets: ['microservice', 'database', 'cache', 'messageQueue', 'storage', 'authService', 'thirdPartyApi'],
  },
  worker: {
    label: 'Worker',
    Icon: Cpu,
    accent: '#eab308',
    category: 'services',
    defaultTechnology: 'Celery / BullMQ',
    defaultName: 'Worker',
    description: 'Background job processor. Consumes tasks from a message queue.',
    allowedTargets: ['database', 'cache', 'storage', 'messageQueue', 'thirdPartyApi'],
  },
  authService: {
    label: 'Auth Service',
    Icon: KeyRound,
    accent: '#a855f7',
    category: 'services',
    defaultTechnology: 'OAuth / JWT / Auth0',
    defaultName: 'Auth Service',
    description: 'Handles authentication and authorization for incoming requests.',
    allowedTargets: ['database', 'cache'],
  },
  cronJob: {
    label: 'Cron Job',
    Icon: Timer,
    accent: '#84cc16',
    category: 'services',
    defaultTechnology: 'Cron / Scheduled Lambda',
    defaultName: 'Cron Job',
    description: 'Runs on a fixed schedule to perform periodic background tasks.',
    allowedTargets: ['database', 'cache', 'messageQueue', 'storage', 'apiServer', 'microservice'],
  },
  serverlessFunction: {
    label: 'Serverless Function',
    Icon: CloudLightning,
    accent: '#fb923c',
    category: 'services',
    defaultTechnology: 'AWS Lambda / Cloud Functions',
    defaultName: 'Function',
    description: 'Stateless, event-triggered compute that scales automatically.',
    allowedTargets: ['database', 'cache', 'messageQueue', 'storage', 'microservice'],
  },
  thirdPartyApi: {
    label: 'Third-Party API',
    Icon: Plug,
    accent: '#0ea5e9',
    category: 'services',
    defaultTechnology: 'Stripe / Twilio / External API',
    defaultName: 'Third-Party API',
    description: 'External service integration outside your own infrastructure.',
    allowedTargets: [],
  },
  database: {
    label: 'Database',
    Icon: Database,
    accent: '#6366f1',
    category: 'data',
    defaultTechnology: 'PostgreSQL / MySQL',
    defaultName: 'Database',
    description: 'Persistent data store. Source of truth for structured data.',
    allowedTargets: ['cache', 'storage'],
  },
  cache: {
    label: 'Cache',
    Icon: Zap,
    accent: '#ef4444',
    category: 'data',
    defaultTechnology: 'Redis / Memcached',
    defaultName: 'Cache',
    description: 'In-memory store for fast reads. Reduces database load.',
    allowedTargets: ['database'],
  },
  messageQueue: {
    label: 'Message Queue',
    Icon: Radio,
    accent: '#f59e0b',
    category: 'data',
    defaultTechnology: 'RabbitMQ / Kafka',
    defaultName: 'Message Queue',
    description: 'Async message broker decoupling producers from consumers.',
    allowedTargets: ['worker', 'microservice', 'apiServer', 'serverlessFunction'],
  },
  storage: {
    label: 'Object Storage',
    Icon: HardDrive,
    accent: '#6b7280',
    category: 'data',
    defaultTechnology: 'S3 / GCS',
    defaultName: 'Storage',
    description: 'Blob/object store for files, images, backups, and logs.',
    allowedTargets: [],
  },
};

export const NODE_CATEGORIES: {
  id: 'infrastructure' | 'services' | 'data';
  label: string;
  types: NodeType[];
}[] = [
  {
    id: 'infrastructure',
    label: 'Infrastructure',
    types: ['user', 'cdn', 'dns', 'waf', 'loadBalancer', 'apiGateway'],
  },
  {
    id: 'services',
    label: 'Services',
    types: ['apiServer', 'microservice', 'worker', 'authService', 'cronJob', 'serverlessFunction', 'thirdPartyApi'],
  },
  {
    id: 'data',
    label: 'Data',
    types: ['database', 'cache', 'messageQueue', 'storage'],
  },
];
