import type { NodeCategoryGroup, NodeType, NodeTypeConfig } from '@/types';
import { imgIcon } from './icon';

const ACCENT = '#FF9900';
const icon = (name: string) => imgIcon(`/icons/aws/${name}.svg`);

export const AWS_NODE_CONFIG: Partial<Record<NodeType, NodeTypeConfig>> = {
  'aws-cloudfront': {
    label: 'CloudFront',
    Icon: icon('cloudfront'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'aws',
    defaultTechnology: 'Amazon CloudFront',
    defaultName: 'CloudFront',
    description: "Amazon's global CDN — caches and serves content from edge locations close to users.",
    allowedTargets: ['aws-elb', 'aws-api-gateway', 'aws-ec2'],
  },
  'aws-route53': {
    label: 'Route 53',
    Icon: icon('route53'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'aws',
    defaultTechnology: 'Amazon Route 53',
    defaultName: 'Route 53',
    description: "Amazon's DNS web service — routes end-user requests to AWS or on-prem endpoints.",
    allowedTargets: ['aws-cloudfront', 'aws-waf', 'aws-elb', 'aws-api-gateway'],
  },
  'aws-waf': {
    label: 'AWS WAF',
    Icon: icon('waf'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'aws',
    defaultTechnology: 'AWS WAF',
    defaultName: 'AWS WAF',
    description: 'Filters and blocks malicious web traffic before it reaches your application.',
    allowedTargets: ['aws-cloudfront', 'aws-elb', 'aws-api-gateway'],
  },
  'aws-elb': {
    label: 'Elastic Load Balancing',
    Icon: icon('elb'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'aws',
    defaultTechnology: 'Elastic Load Balancing',
    defaultName: 'ELB',
    description: 'Distributes incoming traffic across multiple EC2 instances or containers.',
    allowedTargets: ['aws-api-gateway', 'aws-ec2', 'aws-ecs', 'aws-cloudwatch'],
  },
  'aws-api-gateway': {
    label: 'API Gateway',
    Icon: icon('api-gateway'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'aws',
    defaultTechnology: 'Amazon API Gateway',
    defaultName: 'API Gateway',
    description: 'Fully managed entry point for REST/HTTP/WebSocket APIs, with auth and throttling built in.',
    allowedTargets: ['aws-ec2', 'aws-ecs', 'aws-lambda', 'aws-cognito', 'aws-cloudwatch'],
  },
  'aws-cloudwatch': {
    label: 'CloudWatch',
    Icon: icon('cloudwatch'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'aws',
    defaultTechnology: 'Amazon CloudWatch',
    defaultName: 'CloudWatch',
    description: 'Collects metrics, logs, and alarms for AWS resources and applications.',
    allowedTargets: ['aws-sns'],
  },
  'aws-ec2': {
    label: 'EC2',
    Icon: icon('ec2'),
    accent: ACCENT,
    category: 'services',
    provider: 'aws',
    defaultTechnology: 'Amazon EC2',
    defaultName: 'EC2',
    description: 'Resizable virtual servers for running application code in the cloud.',
    allowedTargets: ['aws-ecs', 'aws-rds', 'aws-dynamodb', 'aws-elasticache', 'aws-sqs', 'aws-s3', 'aws-cognito', 'aws-opensearch', 'aws-cloudwatch', 'thirdPartyApi'],
  },
  'aws-ecs': {
    label: 'ECS',
    Icon: icon('ecs'),
    accent: ACCENT,
    category: 'services',
    provider: 'aws',
    defaultTechnology: 'Amazon ECS',
    defaultName: 'ECS',
    description: 'Fully managed container orchestration for running Docker workloads.',
    allowedTargets: ['aws-ecs', 'aws-rds', 'aws-dynamodb', 'aws-elasticache', 'aws-sqs', 'aws-s3', 'aws-cognito', 'aws-opensearch', 'aws-cloudwatch', 'thirdPartyApi'],
  },
  'aws-lambda': {
    label: 'Lambda',
    Icon: icon('lambda'),
    accent: ACCENT,
    category: 'services',
    provider: 'aws',
    defaultTechnology: 'AWS Lambda',
    defaultName: 'Lambda',
    description: 'Runs code in response to events without provisioning or managing servers.',
    allowedTargets: ['aws-rds', 'aws-dynamodb', 'aws-elasticache', 'aws-sqs', 'aws-s3', 'aws-sns', 'aws-cloudwatch', 'thirdPartyApi'],
  },
  'aws-cognito': {
    label: 'Cognito',
    Icon: icon('cognito'),
    accent: ACCENT,
    category: 'services',
    provider: 'aws',
    defaultTechnology: 'Amazon Cognito',
    defaultName: 'Cognito',
    description: 'Handles user sign-up, sign-in, and access control for web and mobile apps.',
    allowedTargets: ['aws-dynamodb', 'aws-rds'],
  },
  'aws-eventbridge': {
    label: 'EventBridge',
    Icon: icon('eventbridge'),
    accent: ACCENT,
    category: 'services',
    provider: 'aws',
    defaultTechnology: 'Amazon EventBridge',
    defaultName: 'EventBridge',
    description: 'Serverless event bus that can also trigger targets on a schedule.',
    allowedTargets: ['aws-lambda', 'aws-ec2', 'aws-ecs', 'aws-sqs', 'aws-sns'],
  },
  'aws-rds': {
    label: 'RDS',
    Icon: icon('rds'),
    accent: ACCENT,
    category: 'data',
    provider: 'aws',
    defaultTechnology: 'Amazon RDS',
    defaultName: 'RDS',
    description: 'Managed relational database supporting Postgres, MySQL, and more.',
    allowedTargets: ['aws-elasticache', 'aws-s3'],
  },
  'aws-dynamodb': {
    label: 'DynamoDB',
    Icon: icon('dynamodb'),
    accent: ACCENT,
    category: 'data',
    provider: 'aws',
    defaultTechnology: 'Amazon DynamoDB',
    defaultName: 'DynamoDB',
    description: 'Fully managed, serverless NoSQL key-value and document database.',
    allowedTargets: ['aws-elasticache'],
  },
  'aws-elasticache': {
    label: 'ElastiCache',
    Icon: icon('elasticache'),
    accent: ACCENT,
    category: 'data',
    provider: 'aws',
    defaultTechnology: 'Amazon ElastiCache',
    defaultName: 'ElastiCache',
    description: 'Managed in-memory data store for Redis or Memcached.',
    allowedTargets: ['aws-rds', 'aws-dynamodb'],
  },
  'aws-sqs': {
    label: 'SQS',
    Icon: icon('sqs'),
    accent: ACCENT,
    category: 'data',
    provider: 'aws',
    defaultTechnology: 'Amazon SQS',
    defaultName: 'SQS',
    description: 'Fully managed message queuing for decoupling and scaling microservices.',
    allowedTargets: ['aws-lambda', 'aws-ecs', 'aws-ec2', 'aws-sns'],
  },
  'aws-s3': {
    label: 'S3',
    Icon: icon('s3'),
    accent: ACCENT,
    category: 'data',
    provider: 'aws',
    defaultTechnology: 'Amazon S3',
    defaultName: 'S3',
    description: 'Object storage built to store and retrieve any amount of data.',
    allowedTargets: [],
  },
  'aws-opensearch': {
    label: 'OpenSearch Service',
    Icon: icon('opensearch'),
    accent: ACCENT,
    category: 'data',
    provider: 'aws',
    defaultTechnology: 'Amazon OpenSearch Service',
    defaultName: 'OpenSearch',
    description: 'Managed Elasticsearch-compatible service for search and log analytics.',
    allowedTargets: [],
  },
  'aws-redshift': {
    label: 'Redshift',
    Icon: icon('redshift'),
    accent: ACCENT,
    category: 'data',
    provider: 'aws',
    defaultTechnology: 'Amazon Redshift',
    defaultName: 'Redshift',
    description: 'Fully managed data warehouse for large-scale analytical queries.',
    allowedTargets: [],
  },
  'aws-sns': {
    label: 'SNS',
    Icon: icon('sns'),
    accent: ACCENT,
    category: 'services',
    provider: 'aws',
    defaultTechnology: 'Amazon SNS',
    defaultName: 'SNS',
    description: 'Fully managed pub/sub messaging for app-to-app and app-to-person notifications.',
    allowedTargets: ['aws-lambda', 'thirdPartyApi'],
  },
};

export const AWS_CATEGORIES: NodeCategoryGroup[] = [
  { id: 'infrastructure', label: 'Infrastructure', types: ['aws-cloudfront', 'aws-route53', 'aws-waf', 'aws-elb', 'aws-api-gateway', 'aws-cloudwatch'] },
  { id: 'services', label: 'Services', types: ['aws-ec2', 'aws-ecs', 'aws-lambda', 'aws-cognito', 'aws-eventbridge', 'aws-sns'] },
  { id: 'data', label: 'Data', types: ['aws-rds', 'aws-dynamodb', 'aws-elasticache', 'aws-sqs', 'aws-s3', 'aws-opensearch', 'aws-redshift'] },
];
