import type { NodeCategoryGroup, NodeType, NodeTypeConfig } from '@/types';
import { imgIcon } from './icon';

const ACCENT = '#0078D4';
const icon = (name: string) => imgIcon(`/icons/azure/${name}.svg`);

export const AZURE_NODE_CONFIG: Partial<Record<NodeType, NodeTypeConfig>> = {
  'azure-cdn': {
    label: 'Front Door & CDN',
    Icon: icon('cdn'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'azure',
    defaultTechnology: 'Azure Front Door / CDN',
    defaultName: 'Azure CDN',
    description: "Microsoft's global CDN — caches and accelerates content delivery at the edge.",
    allowedTargets: ['azure-load-balancer', 'azure-api-management', 'azure-vm'],
  },
  'azure-dns': {
    label: 'DNS Zones',
    Icon: icon('dns'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'azure',
    defaultTechnology: 'Azure DNS',
    defaultName: 'Azure DNS',
    description: 'Hosts DNS domains and routes traffic for Azure resources.',
    allowedTargets: ['azure-cdn', 'azure-waf', 'azure-load-balancer', 'azure-api-management'],
  },
  'azure-waf': {
    label: 'Web App Firewall',
    Icon: icon('waf'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'azure',
    defaultTechnology: 'Azure WAF',
    defaultName: 'Azure WAF',
    description: 'Protects web apps from common exploits and bots at the edge.',
    allowedTargets: ['azure-cdn', 'azure-load-balancer', 'azure-api-management'],
  },
  'azure-load-balancer': {
    label: 'Load Balancer',
    Icon: icon('load-balancer'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'azure',
    defaultTechnology: 'Azure Load Balancer',
    defaultName: 'Load Balancer',
    description: 'Distributes traffic across VMs or containers for high availability.',
    allowedTargets: ['azure-api-management', 'azure-vm', 'azure-aks', 'azure-monitor'],
  },
  'azure-api-management': {
    label: 'API Management',
    Icon: icon('api-management'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'azure',
    defaultTechnology: 'Azure API Management',
    defaultName: 'API Management',
    description: 'Publishes, secures, and monitors APIs behind a single gateway.',
    allowedTargets: ['azure-vm', 'azure-aks', 'azure-functions', 'azure-entra', 'azure-monitor'],
  },
  'azure-monitor': {
    label: 'Azure Monitor',
    Icon: icon('monitor'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'azure',
    defaultTechnology: 'Azure Monitor',
    defaultName: 'Azure Monitor',
    description: 'Collects metrics, logs, and telemetry across Azure resources and apps.',
    allowedTargets: ['azure-notification-hubs'],
  },
  'azure-vm': {
    label: 'Virtual Machine',
    Icon: icon('vm'),
    accent: ACCENT,
    category: 'services',
    provider: 'azure',
    defaultTechnology: 'Azure Virtual Machines',
    defaultName: 'Azure VM',
    description: 'On-demand, scalable compute for running application workloads.',
    allowedTargets: ['azure-aks', 'azure-sql-database', 'azure-cosmos-db', 'azure-cache-redis', 'azure-service-bus', 'azure-blob-storage', 'azure-entra', 'azure-cognitive-search', 'azure-monitor', 'thirdPartyApi'],
  },
  'azure-aks': {
    label: 'AKS',
    Icon: icon('aks'),
    accent: ACCENT,
    category: 'services',
    provider: 'azure',
    defaultTechnology: 'Azure Kubernetes Service',
    defaultName: 'AKS',
    description: 'Managed Kubernetes for deploying and scaling containerized apps.',
    allowedTargets: ['azure-sql-database', 'azure-cosmos-db', 'azure-cache-redis', 'azure-service-bus', 'azure-blob-storage', 'azure-entra', 'azure-cognitive-search', 'azure-monitor', 'thirdPartyApi'],
  },
  'azure-functions': {
    label: 'Function Apps',
    Icon: icon('functions'),
    accent: ACCENT,
    category: 'services',
    provider: 'azure',
    defaultTechnology: 'Azure Functions',
    defaultName: 'Function App',
    description: 'Event-driven, serverless compute that runs code on demand.',
    allowedTargets: ['azure-sql-database', 'azure-cosmos-db', 'azure-cache-redis', 'azure-service-bus', 'azure-blob-storage', 'azure-notification-hubs', 'azure-monitor', 'thirdPartyApi'],
  },
  'azure-entra': {
    label: 'Azure AD B2C',
    Icon: icon('entra'),
    accent: ACCENT,
    category: 'services',
    provider: 'azure',
    defaultTechnology: 'Azure AD B2C / Entra',
    defaultName: 'Azure AD B2C',
    description: 'Customer identity and access management for web and mobile apps.',
    allowedTargets: ['azure-cosmos-db', 'azure-sql-database'],
  },
  'azure-scheduler': {
    label: 'Scheduler',
    Icon: icon('scheduler'),
    accent: ACCENT,
    category: 'services',
    provider: 'azure',
    defaultTechnology: 'Azure Logic Apps',
    defaultName: 'Scheduler',
    description: 'Triggers jobs and workflows on a recurring schedule.',
    allowedTargets: ['azure-functions', 'azure-vm', 'azure-aks', 'azure-service-bus', 'azure-notification-hubs'],
  },
  'azure-sql-database': {
    label: 'SQL Database',
    Icon: icon('sql-database'),
    accent: ACCENT,
    category: 'data',
    provider: 'azure',
    defaultTechnology: 'Azure SQL Database',
    defaultName: 'SQL Database',
    description: 'Managed relational database built on the SQL Server engine.',
    allowedTargets: ['azure-cache-redis', 'azure-blob-storage'],
  },
  'azure-cosmos-db': {
    label: 'Cosmos DB',
    Icon: icon('cosmos-db'),
    accent: ACCENT,
    category: 'data',
    provider: 'azure',
    defaultTechnology: 'Azure Cosmos DB',
    defaultName: 'Cosmos DB',
    description: 'Globally distributed, multi-model NoSQL database with low-latency access.',
    allowedTargets: ['azure-cache-redis'],
  },
  'azure-cache-redis': {
    label: 'Cache for Redis',
    Icon: icon('cache-redis'),
    accent: ACCENT,
    category: 'data',
    provider: 'azure',
    defaultTechnology: 'Azure Cache for Redis',
    defaultName: 'Cache for Redis',
    description: 'Managed in-memory data store for fast reads and caching.',
    allowedTargets: ['azure-sql-database', 'azure-cosmos-db'],
  },
  'azure-service-bus': {
    label: 'Service Bus',
    Icon: icon('service-bus'),
    accent: ACCENT,
    category: 'data',
    provider: 'azure',
    defaultTechnology: 'Azure Service Bus',
    defaultName: 'Service Bus',
    description: 'Enterprise message broker with queues and publish/subscribe topics.',
    allowedTargets: ['azure-functions', 'azure-aks', 'azure-vm', 'azure-notification-hubs'],
  },
  'azure-blob-storage': {
    label: 'Blob Storage',
    Icon: icon('blob-storage'),
    accent: ACCENT,
    category: 'data',
    provider: 'azure',
    defaultTechnology: 'Azure Blob Storage',
    defaultName: 'Blob Storage',
    description: 'Object storage for unstructured data such as files, images, and backups.',
    allowedTargets: [],
  },
  'azure-cognitive-search': {
    label: 'Cognitive Search',
    Icon: icon('cognitive-search'),
    accent: ACCENT,
    category: 'data',
    provider: 'azure',
    defaultTechnology: 'Azure Cognitive Search',
    defaultName: 'Cognitive Search',
    description: 'AI-powered search-as-a-service over your content and data.',
    allowedTargets: [],
  },
  'azure-synapse': {
    label: 'Synapse Analytics',
    Icon: icon('synapse'),
    accent: ACCENT,
    category: 'data',
    provider: 'azure',
    defaultTechnology: 'Azure Synapse Analytics',
    defaultName: 'Synapse Analytics',
    description: 'Unified analytics service combining data warehousing and big data.',
    allowedTargets: [],
  },
  'azure-notification-hubs': {
    label: 'Notification Hubs',
    Icon: icon('notification-hubs'),
    accent: ACCENT,
    category: 'services',
    provider: 'azure',
    defaultTechnology: 'Azure Notification Hubs',
    defaultName: 'Notification Hubs',
    description: 'Sends push notifications to iOS, Android, and other platforms at scale.',
    allowedTargets: ['azure-functions', 'thirdPartyApi'],
  },
};

export const AZURE_CATEGORIES: NodeCategoryGroup[] = [
  { id: 'infrastructure', label: 'Infrastructure', types: ['azure-cdn', 'azure-dns', 'azure-waf', 'azure-load-balancer', 'azure-api-management', 'azure-monitor'] },
  { id: 'services', label: 'Services', types: ['azure-vm', 'azure-aks', 'azure-functions', 'azure-entra', 'azure-scheduler', 'azure-notification-hubs'] },
  { id: 'data', label: 'Data', types: ['azure-sql-database', 'azure-cosmos-db', 'azure-cache-redis', 'azure-service-bus', 'azure-blob-storage', 'azure-cognitive-search', 'azure-synapse'] },
];
