import type { NodeCategoryGroup, NodeType, NodeTypeConfig } from '@/types';
import { imgIcon } from './icon';

const ACCENT = '#34A853';
const icon = (name: string) => imgIcon(`/icons/gcp/${name}.svg`);

export const GCP_NODE_CONFIG: Partial<Record<NodeType, NodeTypeConfig>> = {
  'gcp-cloud-cdn': {
    label: 'Cloud CDN',
    Icon: icon('cloud-cdn'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud CDN',
    defaultName: 'Cloud CDN',
    description: "Google's global CDN — caches content at edge locations close to users.",
    allowedTargets: ['gcp-load-balancing', 'gcp-api-gateway', 'gcp-compute-engine'],
  },
  'gcp-cloud-dns': {
    label: 'Cloud DNS',
    Icon: icon('cloud-dns'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud DNS',
    defaultName: 'Cloud DNS',
    description: 'Scalable, reliable DNS service for routing traffic to your services.',
    allowedTargets: ['gcp-cloud-cdn', 'gcp-cloud-armor', 'gcp-load-balancing', 'gcp-api-gateway'],
  },
  'gcp-cloud-armor': {
    label: 'Cloud Armor',
    Icon: icon('cloud-armor'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud Armor',
    defaultName: 'Cloud Armor',
    description: 'Protects applications from DDoS attacks and web exploits at the edge.',
    allowedTargets: ['gcp-cloud-cdn', 'gcp-load-balancing', 'gcp-api-gateway'],
  },
  'gcp-load-balancing': {
    label: 'Cloud Load Balancing',
    Icon: icon('load-balancing'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud Load Balancing',
    defaultName: 'Load Balancing',
    description: 'Distributes traffic across VMs, containers, or serverless backends.',
    allowedTargets: ['gcp-api-gateway', 'gcp-compute-engine', 'gcp-gke', 'gcp-monitoring'],
  },
  'gcp-api-gateway': {
    label: 'API Gateway',
    Icon: icon('api-gateway'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud API Gateway',
    defaultName: 'API Gateway',
    description: 'Fully managed gateway for publishing, securing, and monitoring APIs.',
    allowedTargets: ['gcp-compute-engine', 'gcp-gke', 'gcp-cloud-functions', 'gcp-identity-platform', 'gcp-monitoring'],
  },
  'gcp-monitoring': {
    label: 'Cloud Monitoring',
    Icon: icon('monitoring'),
    accent: ACCENT,
    category: 'infrastructure',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud Monitoring',
    defaultName: 'Cloud Monitoring',
    description: 'Collects metrics, dashboards, and alerts for GCP resources and apps.',
    allowedTargets: [],
  },
  'gcp-compute-engine': {
    label: 'Compute Engine',
    Icon: icon('compute-engine'),
    accent: ACCENT,
    category: 'services',
    provider: 'gcp',
    defaultTechnology: 'Google Compute Engine',
    defaultName: 'Compute Engine',
    description: 'Customizable virtual machines for general-purpose compute workloads.',
    allowedTargets: ['gcp-gke', 'gcp-cloud-sql', 'gcp-firestore', 'gcp-memorystore', 'gcp-pubsub', 'gcp-cloud-storage', 'gcp-identity-platform', 'gcp-monitoring', 'thirdPartyApi'],
  },
  'gcp-gke': {
    label: 'GKE',
    Icon: icon('gke'),
    accent: ACCENT,
    category: 'services',
    provider: 'gcp',
    defaultTechnology: 'Google Kubernetes Engine',
    defaultName: 'GKE',
    description: 'Managed Kubernetes for deploying and scaling containerized apps.',
    allowedTargets: ['gcp-cloud-sql', 'gcp-firestore', 'gcp-memorystore', 'gcp-pubsub', 'gcp-cloud-storage', 'gcp-identity-platform', 'gcp-monitoring', 'thirdPartyApi'],
  },
  'gcp-cloud-functions': {
    label: 'Cloud Functions',
    Icon: icon('cloud-functions'),
    accent: ACCENT,
    category: 'services',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud Functions',
    defaultName: 'Cloud Functions',
    description: 'Event-driven, serverless functions that scale automatically.',
    allowedTargets: ['gcp-cloud-sql', 'gcp-firestore', 'gcp-memorystore', 'gcp-pubsub', 'gcp-cloud-storage', 'gcp-monitoring', 'thirdPartyApi'],
  },
  'gcp-identity-platform': {
    label: 'Identity Platform',
    Icon: icon('identity-platform'),
    accent: ACCENT,
    category: 'services',
    provider: 'gcp',
    defaultTechnology: 'Google Identity Platform',
    defaultName: 'Identity Platform',
    description: 'Adds authentication and identity management to apps and services.',
    allowedTargets: ['gcp-firestore', 'gcp-cloud-sql'],
  },
  'gcp-cloud-scheduler': {
    label: 'Cloud Scheduler',
    Icon: icon('cloud-scheduler'),
    accent: ACCENT,
    category: 'services',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud Scheduler',
    defaultName: 'Cloud Scheduler',
    description: 'Fully managed cron job scheduler for triggering tasks and pipelines.',
    allowedTargets: ['gcp-cloud-functions', 'gcp-compute-engine', 'gcp-gke', 'gcp-pubsub'],
  },
  'gcp-cloud-sql': {
    label: 'Cloud SQL',
    Icon: icon('cloud-sql'),
    accent: ACCENT,
    category: 'data',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud SQL',
    defaultName: 'Cloud SQL',
    description: 'Managed relational database for MySQL, PostgreSQL, and SQL Server.',
    allowedTargets: ['gcp-memorystore', 'gcp-cloud-storage'],
  },
  'gcp-firestore': {
    label: 'Firestore',
    Icon: icon('firestore'),
    accent: ACCENT,
    category: 'data',
    provider: 'gcp',
    defaultTechnology: 'Google Firestore',
    defaultName: 'Firestore',
    description: 'Serverless NoSQL document database with real-time sync.',
    allowedTargets: ['gcp-memorystore'],
  },
  'gcp-memorystore': {
    label: 'Memorystore',
    Icon: icon('memorystore'),
    accent: ACCENT,
    category: 'data',
    provider: 'gcp',
    defaultTechnology: 'Google Memorystore',
    defaultName: 'Memorystore',
    description: 'Managed in-memory store for Redis or Memcached.',
    allowedTargets: ['gcp-cloud-sql', 'gcp-firestore'],
  },
  'gcp-pubsub': {
    label: 'Pub/Sub',
    Icon: icon('pubsub'),
    accent: ACCENT,
    category: 'data',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud Pub/Sub',
    defaultName: 'Pub/Sub',
    description: 'Global, durable messaging for event-driven systems and streaming analytics.',
    allowedTargets: ['gcp-cloud-functions', 'gcp-gke', 'gcp-compute-engine'],
  },
  'gcp-cloud-storage': {
    label: 'Cloud Storage',
    Icon: icon('cloud-storage'),
    accent: ACCENT,
    category: 'data',
    provider: 'gcp',
    defaultTechnology: 'Google Cloud Storage',
    defaultName: 'Cloud Storage',
    description: 'Object storage for any amount of unstructured data.',
    allowedTargets: [],
  },
  'gcp-bigquery': {
    label: 'BigQuery',
    Icon: icon('bigquery'),
    accent: ACCENT,
    category: 'data',
    provider: 'gcp',
    defaultTechnology: 'Google BigQuery',
    defaultName: 'BigQuery',
    description: 'Serverless data warehouse built for fast SQL analytics at scale.',
    allowedTargets: [],
  },
};

export const GCP_CATEGORIES: NodeCategoryGroup[] = [
  { id: 'infrastructure', label: 'Infrastructure', types: ['gcp-cloud-cdn', 'gcp-cloud-dns', 'gcp-cloud-armor', 'gcp-load-balancing', 'gcp-api-gateway', 'gcp-monitoring'] },
  { id: 'services', label: 'Services', types: ['gcp-compute-engine', 'gcp-gke', 'gcp-cloud-functions', 'gcp-identity-platform', 'gcp-cloud-scheduler'] },
  { id: 'data', label: 'Data', types: ['gcp-cloud-sql', 'gcp-firestore', 'gcp-memorystore', 'gcp-pubsub', 'gcp-cloud-storage', 'gcp-bigquery'] },
];
